# Generated by Django 4.0.3 on 2022-05-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Описание')),
                ('preview', models.ImageField(upload_to='images/%Y-%m-%d/', verbose_name='Главное фото')),
                ('on_hover', models.ImageField(upload_to='images/%Y-%m-%d/', verbose_name='Фото при наведении')),
                ('additional', models.ImageField(blank=True, upload_to='images/%Y-%m-%d/', verbose_name='Дополнительное фото')),
                ('low_price', models.CharField(default='', max_length=6, verbose_name='Цена за 2,5 мл')),
                ('medium_price', models.CharField(default='', max_length=6, verbose_name='Цена за 5 мл')),
                ('high_price', models.CharField(default='', max_length=6, verbose_name='Цена за 10 мл')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимость')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Каталог',
                'ordering': ['-time_create', 'title'],
            },
        ),
    ]
