# Generated by Django 4.0.3 on 2022-06-02 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='high_price',
            field=models.CharField(default='', max_length=32, verbose_name='Цена за 10 мл'),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_price',
            field=models.CharField(default='', max_length=32, verbose_name='Цена за 2,5 мл'),
        ),
        migrations.AlterField(
            model_name='product',
            name='medium_price',
            field=models.CharField(default='', max_length=32, verbose_name='Цена за 5 мл'),
        ),
        migrations.CreateModel(
            name='BookmarkProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'db_table': 'bookmark_product',
            },
        ),
    ]
