# Generated by Django 4.0.3 on 2022-06-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_high_price_alter_product_low_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional',
            field=models.ImageField(blank=True, upload_to='images/additional/', verbose_name='Дополнительное фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='on_hover',
            field=models.ImageField(upload_to='images/on_hover/', verbose_name='Фото при наведении'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(upload_to='images/preview/', verbose_name='Главное фото'),
        ),
    ]
