# Generated by Django 4.0.3 on 2022-06-02 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_additional_alter_product_on_hover_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookmarkProduct',
        ),
    ]
