# Generated by Django 4.0.3 on 2022-05-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='additional',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y-%m-%d/', verbose_name='Дополнительное фото'),
        ),
        migrations.AddField(
            model_name='product',
            name='high_price',
            field=models.CharField(default='', max_length=6, verbose_name='Цена за 10 мл'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_price',
            field=models.CharField(default='', max_length=6, verbose_name='Цена за 2,5 мл'),
        ),
        migrations.AddField(
            model_name='product',
            name='medium_price',
            field=models.CharField(default='', max_length=6, verbose_name='Цена за 5 мл'),
        ),
        migrations.AddField(
            model_name='product',
            name='on_hover',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y-%m-%d/', verbose_name='Фото при наведении'),
        ),
        migrations.AddField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y-%m-%d/', verbose_name='Главное фото'),
        ),
    ]
